name: Deploy DK Analyzer Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: azure/docker-login@v1
        with:
          login-server: registry.nymann.dev
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Publish to registry
        run: |
          docker build --cache-from $ONBUILD -t $ONBUILD -f Dockerfile .
          docker push --all-tags registry.nymann.dev/dk-analyzer-frontend
        env:
          ONBUILD: registry.nymann.dev/dk-analyzer-frontend:onbuild
          IMAGE: registry.nymann.dev/dk-analyzer-frontend
